name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
- name: Ensure latest Go
  # You may pin to the exact commit or the version.
  # uses: jmhodges/ensure-latest-go@db34caa373314d0cbf407c7882e864418eb22f1a
  uses: jmhodges/ensure-latest-go@v1.0.2
  with:
    # A comma-seperated list of file paths to not update.
    exclude: # optional, default is 
    # A comma-seperated list of Dockerfiles to update when a new Go version is released. If set, it will override the default behavior of updating any `golang` image Dockerfile in the repo.
    dockerfiles: # optional, default is 
    # A comma-seperated list of Travis CI config files to update when a new Go version is released. If set, it will override the default behavior of updating (but not creating) the "go" setting in a top-level .travis.yml file.
    travisfiles: # optional, default is 
